databases:
  - name: KenzBooks
    databaseName: kenzbooks_oo5e
    user: kenzbooks

services:
  - type: web
    name: KenzBookz
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: KenzBooks
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false